# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # Use the latest version of Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: ["3.10"]
        os: [ubuntu-latest]
    # Define the workflow steps
    steps:
    # Checkout the code of the repository
        - name: Check out Repository Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        # Setup Python for the current language version
        - name: Setup Python ${{ matrix.python-version }}
          if: always()
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        # Install pip
        - name: Install Pip
          if: always()
          run: |
            pip install -U pip
            python -m pip install --user pipx
        # Run GatorGrader: see config/gatorgrade.yml
        - name: Run GatorGrader with GatorGrade
          run:  |
            pip install git+https://github.com/GatorEducator/gatorgrade.git@feat/time-in-report
            gatorgrade --config config/gatorgrade.yml --report env md GITHUB_STEP_SUMMARY
  
        - name: Get current time
          uses: josStorer/get-current-time@v2
          if: always()
          id: current-time
          with:
            format: YYYYMMDD-HH
            utcOffset: "+08:00"
          
        - name: write branch
          uses: GatorEducator/BranchWrite@v1.0.1
          if: always()
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            branch: insight
            path: insight/hello-action-${{steps.current-time.outputs.formattedTime}}.yml
            source: env
            source-arg: JSON_REPORT
